
package quanlyhocvien.view;

import java.util.ArrayList;
import java.util.List;
import quanlyhocvien.bean.DanhMucBean;
import quanlyhocvien.controller.ChuyenManHinhController;

/**
 *
 * @author TUAN
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("QUẢN LÝ HỌC VIÊN");
        ChuyenManHinhController controller = new ChuyenManHinhController(jpn_view);
        controller.setView(jpn_trangchu, jlb_trangchu);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu",jpn_trangchu,jlb_trangchu));
        listItem.add(new DanhMucBean("HocVien",jpn_hocvien,jlb_hocvien));
        listItem.add(new DanhMucBean("KhoaHoc",jpn_khoahoc,jlb_khoahoc));
        listItem.add(new DanhMucBean("LopHoc",jpn_lophoc,jlb_lophoc));
        listItem.add(new DanhMucBean("ThongKe",jpn_thongke,jlb_thongke));
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_root = new javax.swing.JPanel();
        jpn_menu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpn_trangchu = new javax.swing.JPanel();
        jlb_trangchu = new javax.swing.JLabel();
        jpn_hocvien = new javax.swing.JPanel();
        jlb_hocvien = new javax.swing.JLabel();
        jpn_khoahoc = new javax.swing.JPanel();
        jlb_khoahoc = new javax.swing.JLabel();
        jpn_lophoc = new javax.swing.JPanel();
        jlb_lophoc = new javax.swing.JLabel();
        jpn_thongke = new javax.swing.JPanel();
        jlb_thongke = new javax.swing.JLabel();
        jpn_view = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn_menu.setBackground(new java.awt.Color(82, 83, 81));

        jPanel4.setBackground(new java.awt.Color(232, 64, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyhocvien/images/read.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ HỌC VIÊN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jpn_trangchu.setBackground(new java.awt.Color(78, 175, 80));

        jlb_trangchu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlb_trangchu.setForeground(new java.awt.Color(255, 255, 255));
        jlb_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyhocvien/images/desktop.png"))); // NOI18N
        jlb_trangchu.setText("Màn hình chính");

        javax.swing.GroupLayout jpn_trangchuLayout = new javax.swing.GroupLayout(jpn_trangchu);
        jpn_trangchu.setLayout(jpn_trangchuLayout);
        jpn_trangchuLayout.setHorizontalGroup(
            jpn_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_trangchuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpn_trangchuLayout.setVerticalGroup(
            jpn_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_trangchuLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jlb_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpn_hocvien.setBackground(new java.awt.Color(78, 175, 80));

        jlb_hocvien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlb_hocvien.setForeground(new java.awt.Color(255, 255, 255));
        jlb_hocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyhocvien/images/student.png"))); // NOI18N
        jlb_hocvien.setText("Quản lý học viên");

        javax.swing.GroupLayout jpn_hocvienLayout = new javax.swing.GroupLayout(jpn_hocvien);
        jpn_hocvien.setLayout(jpn_hocvienLayout);
        jpn_hocvienLayout.setHorizontalGroup(
            jpn_hocvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_hocvienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_hocvien, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_hocvienLayout.setVerticalGroup(
            jpn_hocvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_hocvienLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jlb_hocvien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpn_khoahoc.setBackground(new java.awt.Color(78, 175, 80));

        jlb_khoahoc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlb_khoahoc.setForeground(new java.awt.Color(255, 255, 255));
        jlb_khoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyhocvien/images/online-course.png"))); // NOI18N
        jlb_khoahoc.setText("Quản lý khóa học");

        javax.swing.GroupLayout jpn_khoahocLayout = new javax.swing.GroupLayout(jpn_khoahoc);
        jpn_khoahoc.setLayout(jpn_khoahocLayout);
        jpn_khoahocLayout.setHorizontalGroup(
            jpn_khoahocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_khoahocLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_khoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_khoahocLayout.setVerticalGroup(
            jpn_khoahocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_khoahocLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_khoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpn_lophoc.setBackground(new java.awt.Color(78, 175, 80));

        jlb_lophoc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlb_lophoc.setForeground(new java.awt.Color(255, 255, 255));
        jlb_lophoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyhocvien/images/training.png"))); // NOI18N
        jlb_lophoc.setText("Quản lý lớp học");

        javax.swing.GroupLayout jpn_lophocLayout = new javax.swing.GroupLayout(jpn_lophoc);
        jpn_lophoc.setLayout(jpn_lophocLayout);
        jpn_lophocLayout.setHorizontalGroup(
            jpn_lophocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_lophocLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_lophoc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_lophocLayout.setVerticalGroup(
            jpn_lophocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_lophocLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_lophoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpn_thongke.setBackground(new java.awt.Color(78, 175, 80));

        jlb_thongke.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlb_thongke.setForeground(new java.awt.Color(255, 255, 255));
        jlb_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyhocvien/images/graph.png"))); // NOI18N
        jlb_thongke.setText("Thống kê dữ liệu");

        javax.swing.GroupLayout jpn_thongkeLayout = new javax.swing.GroupLayout(jpn_thongke);
        jpn_thongke.setLayout(jpn_thongkeLayout);
        jpn_thongkeLayout.setHorizontalGroup(
            jpn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_thongkeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_thongkeLayout.setVerticalGroup(
            jpn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_thongkeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlb_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpn_menuLayout = new javax.swing.GroupLayout(jpn_menu);
        jpn_menu.setLayout(jpn_menuLayout);
        jpn_menuLayout.setHorizontalGroup(
            jpn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpn_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpn_lophoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpn_khoahoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpn_trangchu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpn_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpn_hocvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jpn_menuLayout.setVerticalGroup(
            jpn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_menuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpn_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpn_hocvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpn_khoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpn_lophoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpn_view.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jpn_viewLayout = new javax.swing.GroupLayout(jpn_view);
        jpn_view.setLayout(jpn_viewLayout);
        jpn_viewLayout.setHorizontalGroup(
            jpn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jpn_viewLayout.setVerticalGroup(
            jpn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpn_rootLayout = new javax.swing.GroupLayout(jpn_root);
        jpn_root.setLayout(jpn_rootLayout);
        jpn_rootLayout.setHorizontalGroup(
            jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_rootLayout.createSequentialGroup()
                .addComponent(jpn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_rootLayout.setVerticalGroup(
            jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlb_hocvien;
    private javax.swing.JLabel jlb_khoahoc;
    private javax.swing.JLabel jlb_lophoc;
    private javax.swing.JLabel jlb_thongke;
    private javax.swing.JLabel jlb_trangchu;
    private javax.swing.JPanel jpn_hocvien;
    private javax.swing.JPanel jpn_khoahoc;
    private javax.swing.JPanel jpn_lophoc;
    private javax.swing.JPanel jpn_menu;
    private javax.swing.JPanel jpn_root;
    private javax.swing.JPanel jpn_thongke;
    private javax.swing.JPanel jpn_trangchu;
    private javax.swing.JPanel jpn_view;
    // End of variables declaration//GEN-END:variables
}
