/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyhocvien.view;

import java.util.List;
import quanlyhocvien.controller.LopHocChiTietInfoController;
import quanlyhocvien.model.HocVien;
import quanlyhocvien.model.HocVienLopHoc;

/**
 *
 * @author xuannang
 */
public class ThongTinCuTheLopJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinCuTheLopJFrame
     */
    public ThongTinCuTheLopJFrame(int ma_lop_hoc, List<HocVienLopHoc> listHvlh, List<HocVien> listHv) {
        initComponents();
        
        LopHocChiTietInfoController lop_hoc_chi_tiet_info_controller = new LopHocChiTietInfoController(jpn_view,btn_add, jtf_search,
                 jLabelGiaTriTenLop,jLabelGiaTriSiSo,jLabelGiaTriLichHoc);
        lop_hoc_chi_tiet_info_controller.setView(ma_lop_hoc, listHv);
        lop_hoc_chi_tiet_info_controller.setDatatoTable(listHvlh, listHv);
        lop_hoc_chi_tiet_info_controller.setEven();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_root = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jtf_search = new javax.swing.JTextField();
        jLabelTenLop = new javax.swing.JLabel();
        jLabelGiaTriTenLop = new javax.swing.JLabel();
        jLabelSiSo = new javax.swing.JLabel();
        jLabelGiaTriSiSo = new javax.swing.JLabel();
        jLabelLichHoc = new javax.swing.JLabel();
        jLabelGiaTriLichHoc = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jpn_view = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSearch.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelSearch.setText("Tìm theo tên:");

        jtf_search.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jtf_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_searchActionPerformed(evt);
            }
        });

        jLabelTenLop.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelTenLop.setText("Lớp :");

        jLabelGiaTriTenLop.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelGiaTriTenLop.setText("jLabel2");

        jLabelSiSo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelSiSo.setText("Số học viên :");

        jLabelGiaTriSiSo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelGiaTriSiSo.setText("jLabel2");

        jLabelLichHoc.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelLichHoc.setText("Lịch học :");

        jLabelGiaTriLichHoc.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelGiaTriLichHoc.setText("jLabel2");

        btn_add.setBackground(new java.awt.Color(76, 175, 80));
        btn_add.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("+Thêm học viên");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_viewLayout = new javax.swing.GroupLayout(jpn_view);
        jpn_view.setLayout(jpn_viewLayout);
        jpn_viewLayout.setHorizontalGroup(
            jpn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpn_viewLayout.setVerticalGroup(
            jpn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpn_rootLayout = new javax.swing.GroupLayout(jpn_root);
        jpn_root.setLayout(jpn_rootLayout);
        jpn_rootLayout.setHorizontalGroup(
            jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_rootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_rootLayout.createSequentialGroup()
                        .addComponent(jLabelTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGiaTriTenLop))
                    .addGroup(jpn_rootLayout.createSequentialGroup()
                        .addComponent(jLabelSiSo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGiaTriSiSo))
                    .addGroup(jpn_rootLayout.createSequentialGroup()
                        .addComponent(jLabelLichHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGiaTriLichHoc)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpn_rootLayout.createSequentialGroup()
                .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addContainerGap())
            .addComponent(jpn_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpn_rootLayout.setVerticalGroup(
            jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_rootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGiaTriTenLop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSiSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGiaTriSiSo))
                .addGap(3, 3, 3)
                .addGroup(jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLichHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGiaTriLichHoc))
                .addGap(82, 82, 82)
                .addGroup(jpn_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_search)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jpn_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpn_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_searchActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel jLabelGiaTriLichHoc;
    private javax.swing.JLabel jLabelGiaTriSiSo;
    private javax.swing.JLabel jLabelGiaTriTenLop;
    private javax.swing.JLabel jLabelLichHoc;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSiSo;
    private javax.swing.JLabel jLabelTenLop;
    private javax.swing.JPanel jpn_root;
    private javax.swing.JPanel jpn_view;
    private javax.swing.JTextField jtf_search;
    // End of variables declaration//GEN-END:variables
}
